spring:
  application:
    name: academic-management-system
  datasource:
    url: jdbc:oracle:thin:@ora-02.db.lab.etf.unsa.ba:1521:ETFDB
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 120000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /academic-management-system

security:
  jwt:
    secret-key: ${JWT_TOKEN}
    expiration-ms: 86400000

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG