CREATE SCHEMA IF NOT EXISTS NBP;

CREATE TABLE NBP.NBP_USER
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD     VARCHAR(255) NOT NULL,
    USERNAME     VARCHAR(255) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(255),
    BIRTH_DATE   TIMESTAMP,
    ADDRESS_ID   BIGINT,
    ROLE_ID      BIGINT       NOT NULL,
    DELETED      TIMESTAMP
);

CREATE TABLE NBP_SEMESTER
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    END_DATE   TIMESTAMP   NOT NULL,
    NAME       VARCHAR(50) NOT NULL,
    START_DATE TIMESTAMP   NOT NULL
);